export interface IinsertAnnounce {
  type?: string
  houseNumber?: string
  moo?: string
  soi?: string
  road?: string
  province?: string
  district?: string
  subdistrict?: string
  zipcode?: string
  floor?: string
  bedroom?: string
  bathroom?: string
  parking?: string
  direction?: string
  furniture?: string
  rai?: string
  ngan?: string
  squareWa?: string
  squareMeter?: string
  salePrice?: string
  rentalCommonfee?: string
  roomStatus?: string
  agent?: string
  commonFee?: string[]
  security?: string[]
  facilities?: string[]
  topicName?: string
  moreDetails?: string
  coverPhoto?: string
  photo?: string[]
}
